#  It is triggered on pull requests to the main branch
name: Terraform Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0 # Adjust to your required version

      - name: Initialize Terraform
        run: terraform init

      - name: Check Terraform formatting
        run: terraform fmt -check

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform plan