# triggered on push to the main branch
name: 'Terraform Deploy'
# added comment for PR
on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: us-west-2
        role-session-name: GithubActions

    - name: Terraform Init
      # working-directory: terraform-example
      run: terraform init

    - name: Terraform Apply
      # working-directory: terraform-example
      run: terraform apply